Fix Vertex OpenAPI specification to specify UTF-8 charset on every api operation
killbill/killbill-vertex-plugin pull request #30
Opened 2023-06-05 20:28 UTC by vlaskhilkevich

Addresses https://packet.atlassian.net/browse/ENG-21930.

Needed as currently `ISO-8859-1` is used by default in api client generated by `apache-httpclient`.
More info [https://github.com/OpenAPITools/openapi-generator/issues/12797](https://github.com/OpenAPITools/openapi-generator/issues/12797)

Testing:
- Tested by adding `UTF-8` char in on of the addresses in `VertexTaxCalculatorITest`.
- Confirmed locally issue is not reproduced after applying the fix.

2023-06-06 22:02 UTC, singh-sukhvir requested changes
Looks gd. Request to create a separate test for special-char address rather than existing test.

2023-06-06 22:02 UTC, singh-sukhvir commented on src/test/java/org/killbill/billing/plugin/vertex/VertexTaxCalculatorITest.java
> +        account3 = TestUtils.buildAccount(Currency.USD, "118 N Clark St Ste 100" + 'Ä', null, "Chicago", "IL", "60602", "US");
Also, maybe we should have a separate test for testing special char use-case e.g. `testCompute_WhenAddressHasSpecialCharacters`

2023-06-07 13:08 UTC, vlaskhilkevich commented on src/test/java/org/killbill/billing/plugin/vertex/VertexTaxCalculatorITest.java
> +        account3 = TestUtils.buildAccount(Currency.USD, "118 N Clark St Ste 100" + 'Ä', null, "Chicago", "IL", "60602", "US");
Added separate test with the failing address for kb_account d651a190-7660-43e2-a09f-25ccbe9c326e from Germany

2023-06-07 17:11 UTC, closed without merging

2023-06-07 17:14 UTC, vlaskhilkevich commented
Closed due to strange issue when git was not updating PR after changes in the branch pushed. New PR - https://github.com/killbill/killbill-vertex-plugin/pull/31